#!/usr/bin/env bash
# One-time server preparation: generate real secrets and lock down the firewall.
# Safe to re-run — it never regenerates an existing secret.
#
#   ./scripts/server-setup.sh <site-address> [acme-email]
#   ./scripts/server-setup.sh 51-250-17-150.sslip.io
set -euo pipefail

SITE="${1:-}"
EMAIL="${2:-}"
cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ -z "$SITE" ]; then
  echo "usage: $0 <site-address> [acme-email]" >&2
  echo "  e.g. $0 51-250-17-150.sslip.io" >&2
  exit 2
fi

# ---- secrets ----------------------------------------------------------
# .env is generated ONCE and then left alone. Regenerating POSTGRES_PASSWORD
# after the data volume exists would lock the services out of their own
# database, so an existing value always wins.
if [ -f .env ]; then
  echo "  .env already exists — keeping the existing secrets"
  # shellcheck disable=SC1091
  . ./.env
else
  echo "  generating .env"
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  JWT_SECRET="$(openssl rand -hex 48)"
  INTERNAL_TOKEN="$(openssl rand -hex 32)"
  DASH_USER="admin"
  DASH_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
  # Caddy stores a bcrypt hash, never the password itself.
  DASH_PASSWORD_HASH="$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "$DASH_PASSWORD")"

  umask 077
  # Every value here must be free of '$'. This file is both sourced by bash
  # (set -u) and interpolated by Compose, and a stray '$' breaks both — which
  # is exactly why the bcrypt hash lives in caddy.env instead.
  cat > .env <<EOF
# Generated by scripts/server-setup.sh — DO NOT COMMIT.
# Regenerating POSTGRES_PASSWORD after first start will lock out the database.
SITE_ADDRESS=$SITE
ACME_EMAIL=$EMAIL

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
INTERNAL_TOKEN=$INTERNAL_TOKEN

# prod hides the OTP devCode, disables the 7777 master code and requires
# verificationId on login. Set to dev ONLY while seeding demo data.
APP_ENV=prod

# Caddy injects ADMIN_TOKEN server-side so the JWT never reaches the browser.
# Filled in by scripts/seed-prod.sh via scripts/mint-admin-token.sh.
DASH_USER=$DASH_USER
ADMIN_TOKEN=
EOF
  chmod 600 .env

  # A bcrypt hash starts '\$2a\$14\$...'. Compose's env_file passes values
  # through literally with no interpolation, and nothing sources this file,
  # so the dollars survive intact.
  printf 'DASH_PASSWORD_HASH=%s\n' "$DASH_PASSWORD_HASH" > caddy.env
  chmod 600 caddy.env

  cat > .dashboard-credentials <<EOF
Dashboard login for https://$SITE/
  user:     $DASH_USER
  password: $DASH_PASSWORD
EOF
  chmod 600 .dashboard-credentials
  echo
  echo "  ==> dashboard password saved to .dashboard-credentials (chmod 600)"
  echo "      user=$DASH_USER  password=$DASH_PASSWORD"
  echo
fi

# Keep SITE_ADDRESS in step if it was passed differently on a re-run.
if ! grep -q "^SITE_ADDRESS=$SITE$" .env; then
  sed -i "s|^SITE_ADDRESS=.*|SITE_ADDRESS=$SITE|" .env
  echo "  SITE_ADDRESS updated to $SITE"
fi

# ---- firewall ---------------------------------------------------------
# Docker publishes ports by writing iptables rules that bypass ufw, which is
# why the gateway binds to 127.0.0.1 in docker-compose.prod.yml rather than
# relying on the firewall to hide it.
if command -v ufw >/dev/null 2>&1; then
  sudo ufw allow 22/tcp   >/dev/null
  sudo ufw allow 80/tcp   >/dev/null
  sudo ufw allow 443/tcp  >/dev/null
  sudo ufw --force enable >/dev/null
  echo "  firewall: 22, 80, 443 open"
  sudo ufw status | sed 's/^/    /'
else
  echo "  ufw not installed — skipping firewall"
fi

echo
echo "done. next: ./scripts/deploy.sh"
