#!/usr/bin/env bash
# One-time server preparation: generate real secrets and lock down the firewall.
# Safe to re-run — it never regenerates an existing secret.
#
#   ./scripts/server-setup.sh <site-address> [acme-email]
#   ./scripts/server-setup.sh 51-250-17-150.sslip.io
set -euo pipefail

SITE="${1:-}"
EMAIL="${2:-}"
cd "$(dirname "${BASH_SOURCE[0]}")/.."

if [ -z "$SITE" ]; then
  echo "usage: $0 <site-address> [acme-email]" >&2
  echo "  e.g. $0 51-250-17-150.sslip.io" >&2
  exit 2
fi

# ---- secrets ----------------------------------------------------------
# .env is generated ONCE and then left alone. Regenerating POSTGRES_PASSWORD
# after the data volume exists would lock the services out of their own
# database, so an existing value always wins.
if [ -f .env ]; then
  echo "  .env already exists — keeping the existing secrets"
  # shellcheck disable=SC1091
  . ./.env
else
  echo "  generating .env"
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  JWT_SECRET="$(openssl rand -hex 48)"
  INTERNAL_TOKEN="$(openssl rand -hex 32)"

  umask 077
  # Every value here must be free of '$'. This file is both sourced by bash
  # (set -u) and interpolated by Compose, and a stray '$' breaks both.
  cat > .env <<EOF
# Generated by scripts/server-setup.sh — DO NOT COMMIT.
# Regenerating POSTGRES_PASSWORD after first start will lock out the database.
SITE_ADDRESS=$SITE
ACME_EMAIL=$EMAIL

POSTGRES_PASSWORD=$POSTGRES_PASSWORD
JWT_SECRET=$JWT_SECRET
INTERNAL_TOKEN=$INTERNAL_TOKEN

# prod hides the OTP devCode, disables the 7777 master code and requires
# verificationId on login. Set to dev ONLY while seeding demo data.
APP_ENV=prod

# Phone numbers that may sign in with TEST_OTP_CODE instead of a real SMS.
# The dashboard admin is listed so the back office is reachable before an SMS
# gateway exists. An allowlist, not a mode: no other number is affected.
TEST_PHONES=+998900000001,+998900000101,+998900000102,+998900000103
TEST_OTP_CODE=0000

# Not used by the dashboard any more (it signs in properly); kept for scripting
# admin API calls with curl. Filled in by scripts/seed-prod.sh.
ADMIN_TOKEN=
EOF
  chmod 600 .env
  echo "  .env written with fresh secrets"
fi

# Keep SITE_ADDRESS in step if it was passed differently on a re-run.
if ! grep -q "^SITE_ADDRESS=$SITE$" .env; then
  sed -i "s|^SITE_ADDRESS=.*|SITE_ADDRESS=$SITE|" .env
  echo "  SITE_ADDRESS updated to $SITE"
fi

# ---- firewall ---------------------------------------------------------
# Docker publishes ports by writing iptables rules that bypass ufw, which is
# why the gateway binds to 127.0.0.1 in docker-compose.prod.yml rather than
# relying on the firewall to hide it.
if command -v ufw >/dev/null 2>&1; then
  sudo ufw allow 22/tcp   >/dev/null
  sudo ufw allow 80/tcp   >/dev/null
  sudo ufw allow 443/tcp  >/dev/null
  sudo ufw --force enable >/dev/null
  echo "  firewall: 22, 80, 443 open"
  sudo ufw status | sed 's/^/    /'
else
  echo "  ufw not installed — skipping firewall"
fi

echo
echo "done. next: ./scripts/deploy.sh"
